### ISSUE TITLE
Loading base model from models directory

### ISSUE THREAD

**Issue by swashcap** [lob/hapi-bookshelf-models#34]
I’d like to store the “base” model alongside the other models. Here’s the desired directory structure:

```shell
$ tree lib/models --noreport
lib/models
├── Base.js
├── User.js
└── UserStudyRole.js
```

And here’s the config:

```js
{
  register: require('hap-bookshelf-models'),
  plugins: ['registry', 'virtuals'],
  base: {
    model: require('../models/Base.js'),
  },
  models: path.resolve(__dirname, '../models/'),
}
```

Unfortunately, this errors:

```
Error: Bad model/collection Options: TypeError: Cannot read property 'extend' of undefined
      at Object.exports.register (node_modules/hapi-bookshelf-models/lib/index.js:101:17)
      at Object.target [as register] (node_modules/hapi/node_modules/joi/lib/object.js:79:30)
      at each (node_modules/hapi/lib/plugin.js:317:14)
      at iterate (node_modules/hapi/node_modules/items/lib/index.js:36:13)
      at Object.exports.serial (node_modules/hapi/node_modules/items/lib/index.js:39:9)
      at module.exports.internals.Server.internals.Plugin.register (node_modules/hapi/lib/plugin.js:320:11)
  From previous event:
      at callRegisterThen (lib/utils/register-plugin.js:20:41)
  From previous event:
      at module.exports (lib/utils/register-plugin.js:39:4)
      at server.app.pluginsRegistered.plugins.reduce (lib/index.js:20:22)
      at Array.reduce (native)
      at Object.<anonymous> (lib/index.js:19:40)
      at require (internal/module.js:20:19)
      at getServer (test/utils/get-server.js:4:18)
  From previous event:
      at Object.<anonymous> (test/utils/get-server.js:8:32)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (test/integration/keys.js:6:21)
      at require (internal/module.js:20:19)
      at Array.forEach (native)
      at run (bootstrap_node.js:423:7)
      at startup (bootstrap_node.js:147:9)
      at bootstrap_node.js:538:3
```

The problem is _lib/models/Base.js_ is executed _twice_: once as the “base” model and then as a regular model.

Would you be open to a PR that blacklists the base model from model loading?

**Comment by mgartner** [comment]
@swashcap we aren't accepting PRs (information in the README). But if you would like to take over we can discuss transferring ownership.
